### ISSUE TITLE
Use The Web Beacon API for EventsKit

### ISSUE THREAD

**Issue by mortenbo** [tjek/tjek-js-sdk#161]

**Comment by klarstrup** [comment]
I'd love to use this and get rid of all the local storage pooling nonsense on EventsKit. My idea would be to instead of trying to persist an event backlog, to simply dispatch any events in the in-memory events pool upon `beforeunload`/`visibilitychange`.

Some thoughts:

* `navigator.sendBeacon()` is only supported in slightly newer browsers than our recent support floor of `supports css-grid`  https://caniuse.com/beacon => we lose about 0.04% browser support
* We need to dispatch _all_ remaining pool events on `beforeunload`/`visibilitychange` _synchronously_, but we can batch them to conform to a `dispatchLimit`(currently 100) number of events per `sendBeacon` call.
* `navigator.sendBeacon()` does not give us access to returned data, we can't know if the events validate or need to be retried(also because responses would happen after the page closes :P) => `beforeunload`/`visibilitychange` events lost to the void if wolf is down

**Comment by klarstrup** [comment]
Getting rid of the local-storage pool will also prevent a number of issues that could happen with multiple `EventTracker`s and/or multiple versions of the SDK running at once, as we can move the pool entirely inside the `EventTracker` class.

**Comment by klarstrup** [comment]
Initial implementation https://github.com/tjek/tjek-js-sdk/pull/172

**Comment by mortenbo** [comment]
My thoughts right back at you :D 

- Let's go all-in on Web Beacon API then
- For the migration, we need to exhaust the local storage pool if it exists and then delete it
- beforeunload/visibilitychange is not enough IMO. We should also dispatch for every X events - maybe 10. We don't want to send 300+ events to Wolf on beforeunload. Then we don't need to make a dispatch limit on beforeunload
- It's OK we don't know what Wolf returns. We just have to verify it works in testing because we have Wolf logs

**Comment by klarstrup** [comment]
Nice! I'm happy to more aggressively adopt sendBeacon than in https://github.com/tjek/tjek-js-sdk/pull/172/commits/a757db4fdb9ddebc5ea9fa9907a02052df12c1d6

**Comment by klarstrup** [comment]
One drawback I've come to realize: sendBeacon can only really send as  `multipart/form-data` or JSON in `text/plain`. How do we feel about updating wolf to support one of those? @patrick-jessen

**Comment by patrick-jessen** [comment]
@klarstrup we could add support for `multipart/form-data`, should I whip up a PR?
JSON in `text/plain` is bound to cause issues with body-parsing

**Comment by patrick-jessen** [comment]
Hmm perhaps form-data is so suitable after all. Let's do `text/plain` JSON after all 😅

**Comment by mortenbo** [comment]
Why not form-data? text/plain is icky!

**Comment by patrick-jessen** [comment]
form-data fields would also just be text/plain in our use case.
One way do do it is
```
events: "{ /* json in string */}" // 1st event
events: "{ /* json in string */}" // 2nd event
```
Another
```
data: "{\"events\": [...]}" // this is still json in a string
```

**Comment by mortenbo** [comment]
Nah, then let's do text/plain instead like your PR, IMO.

**Comment by klarstrup** [comment]
we can format `FormData`s like 

```
events[0].pp.id: -Vh8Xfv9
events[0].vt: 5dK1DEMJRNc=
events[0]._e: 1
events[0]._v: 2
events[0]._i: 648a262a-19f9-4485-bdb0-0d0330b97042
events[0]._t: 1677269695
events[0]._a: AAABrQ==
events[1].pp.id: -Vh8Xfv9
events[1].ppp.n: 1
events[1].vt: 2R/ergqt6Uw=
events[1]._e: 2
events[1]._v: 2
events[1]._i: 18e17585-8ce5-4d6d-aab2-0d7f5bbec365
events[1]._t: 1677269695
events[1]._a: AAABrQ==
events[2].pp.id: -Vh8Xfv9
events[2].ppp.n: 2
events[2].vt: RJDX27X6/nU=
events[2]._e: 2
events[2]._v: 2
events[2]._i: c2dd4a66-3e18-4248-95f1-18a939409e97
events[2]._t: 1677269698
events[2]._a: AAABrQ==
```

but this gets encoded like this 


```
------WebKitFormBoundary61H58nXdgoljWRLY
Content-Disposition: form-data; name="events[0].pp.id"

-Vh8Xfv9
------WebKitFormBoundary61H58nXdgoljWRLY
Content-Disposition: form-data; name="events[0].vt"

5dK1DEMJRNc=
------WebKitFormBoundary61H58nXdgoljWRLY
Content-Disposition: form-data; name="events[0]._e"

1
------WebKitFormBoundary61H58nXdgoljWRLY
Content-Disposition: form-data; name="events[0]._v"

2
------WebKitFormBoundary61H58nXdgoljWRLY
Content-Disposition: form-data; name="events[0]._i"

648a262a-19f9-4485-bdb0-0d0330b97042
------WebKitFormBoundary61H58nXdgoljWRLY
Content-Disposition: form-data; name="events[0]._t"

1677269695
------WebKitFormBoundary61H58nXdgoljWRLY
Content-Disposition: form-data; name="events[0]._a"

AAABrQ==
------WebKitFormBoundary61H58nXdgoljWRLY
Content-Disposition: form-data; name="events[1].pp.id"

-Vh8Xfv9
------WebKitFormBoundary61H58nXdgoljWRLY
Content-Disposition: form-data; name="events[1].ppp.n"

1
------WebKitFormBoundary61H58nXdgoljWRLY
Content-Disposition: form-data; name="events[1].vt"

2R/ergqt6Uw=
------WebKitFormBoundary61H58nXdgoljWRLY
Content-Disposition: form-data; name="events[1]._e"

2
------WebKitFormBoundary61H58nXdgoljWRLY
Content-Disposition: form-data; name="events[1]._v"

2
------WebKitFormBoundary61H58nXdgoljWRLY
Content-Disposition: form-data; name="events[1]._i"

18e17585-8ce5-4d6d-aab2-0d7f5bbec365
------WebKitFormBoundary61H58nXdgoljWRLY
Content-Disposition: form-data; name="events[1]._t"

1677269695
------WebKitFormBoundary61H58nXdgoljWRLY
Content-Disposition: form-data; name="events[1]._a"

AAABrQ==
------WebKitFormBoundary61H58nXdgoljWRLY
Content-Disposition: form-data; name="events[2].pp.id"

-Vh8Xfv9
------WebKitFormBoundary61H58nXdgoljWRLY
Content-Disposition: form-data; name="events[2].ppp.n"

2
------WebKitFormBoundary61H58nXdgoljWRLY
Content-Disposition: form-data; name="events[2].vt"

RJDX27X6/nU=
------WebKitFormBoundary61H58nXdgoljWRLY
Content-Disposition: form-data; name="events[2]._e"

2
------WebKitFormBoundary61H58nXdgoljWRLY
Content-Disposition: form-data; name="events[2]._v"

2
------WebKitFormBoundary61H58nXdgoljWRLY
Content-Disposition: form-data; name="events[2]._i"

c2dd4a66-3e18-4248-95f1-18a939409e97
------WebKitFormBoundary61H58nXdgoljWRLY
Content-Disposition: form-data; name="events[2]._t"

1677269698
------WebKitFormBoundary61H58nXdgoljWRLY
Content-Disposition: form-data; name="events[2]._a"

AAABrQ==
------WebKitFormBoundary61H58nXdgoljWRLY--
```


which could well balloon our bandwidth usage

**Comment by mortenbo** [comment]
Let's just continue with text/plain 👍
