### ISSUE TITLE
Broken Link to tjek.com/developers/apps

### ISSUE THREAD

**Issue by ThomJN** [tjek/tjek-js-sdk#186]
The link https://tjek.com/developers/apps appears to be broken and is currently returning a 404 error page. 

Date Observed: 2023-04-01

**Comment by klarstrup** [comment]
Thanks Thom

@mortenbo Do we agree that eleaflet.com should redirect to shopgun.com for geoip redirection to the appropriate ETA brand - not to tjek.com?

**Comment by klarstrup** [comment]
Oh and as for the more immediate issue here's where that link in the readme is supposed to send you @ThomJN https://etilbudsavis.dk/developers/apps

**Comment by mortenbo** [comment]
@klarstrup yes, I agree. I've updated the redirect now so it goes to shopgun.com

@ThomJN Thanks for reporting this. Where did you find this link?

**Comment by ThomJN** [comment]
@mortenbo The link was/is found at https://github.com/tjek/tjek-js-sdk under section "Create an App". Link "create an app" (in screenshot) points to https://eleaflet.com/developers/apps but seems to redirect to the broken link https://tjek.com/developers/apps 

![image](https://user-images.githubusercontent.com/5511853/229471185-c29a0ab0-845f-4346-b0cf-d690adc3fb5f.png)

**Comment by mortenbo** [comment]
@ThomJN Ah, thank you very much! It's fixed now.
