### ISSUE TITLE
 Max retries exceeded with url: /v1/products, sslv3 alert handshake failure

### ISSUE THREAD

**Issue by JohannesHelleve** [tjek/tjek-js-sdk#205]
Dont know why got this error message. Shouldn't the api be able to handle a request of that size? Not that many items at Bunnpris that is on sale?
Kind of new to coding, so help would be apriciated.
Maybe it would be better to do it in js?

The code:
```
import requests
import config

API_KEY = config.api_key

# Make the request to the Tjek API
response = requests.get("https://api.tjek.no/v1/products", headers={"Authorization": "Bearer " + API_KEY})

if response.status_code == 200:
    # Get the products from the response
    products = response.json()["products"]

    # Filter the products by store and sale
    products = [product for product in products if product["brand"] == "Bunnpris" and product["sale"] == True]

     # Print the list of products
    for product in products:
        print(product["name"] + " is on sale for " + product["price"])

else:
    print("Error: " + response.status_code)
```

**Comment by roffe** [comment]
we don't handle DNS for that domain, it's parked at the provider, please use squid-api.tjek.com, api.mattilbud.com or api.etilbudsavis.dk

**Comment by JohannesHelleve** [comment]
Can you provide a link of where i can read more about the api ? Tried this, but didn't work.
`response = requests.get("https://api.mattilbud.com/v1/products", headers={"Authorization": "Bearer " + API_KEY})`
Bard AI came up with the code, maybe i should be more sceptical to what it replies :)

**Comment by mortenbo** [comment]
@JohannesHelleve Haha, nice. I def think Bard AI is wrong here 😄 We don't have an /v1/products API.

Maybe you could try to explain what you'd like to achieve using our API's and then we can help you in the right direction?

**Comment by JohannesHelleve** [comment]
I am trying to get all the items at a store, and see which ones are on sale. The code looks good tho. Or?

**Comment by JohannesHelleve** [comment]
I asked Bard Ai to describe what this repo does. I thought the documentation was diffucult to understand. Is there another place i can read more about the API? Or have i misunderstood entirely what this repo is?

**Comment by JohannesHelleve** [comment]
Can you please explain what this API does? Didn't understand the documentation. @mortenbo Not to be pushy, but kinda felt this issue got forgotten

**Comment by mortenbo** [comment]
@JohannesHelleve Here's the flow:

First, go to https://etilbudsavis.no and create an account with your email

Then, go to https://etilbudsavis.no/developers and create an app.

Then you can go to https://github.com/tjek/tjek-js-sdk to implement the SDK.

To get stores, you can use GET https://squid-api.tjek.com/v2/stores.

It takes dealer_id (e.g. `5b11sm` for Bunnpris), offset, limit.

Then you can call GET https://squid-api.tjek.com/v2/offers?store_id=:id with the store ID you got above.

Remember to always set X-Api-Key as request header with the value you got when creating an app in the step above.

Please note you can't use our API for commercial purposes unless we have an agreement. You are also more than welcome to email me on mr [a t] tjek [punktum] com if you want to continue the dialog.

I hope this helped and I apologize for the poor experience on our side!
