### ISSUE TITLE
Add "Powered by Incito" to Incitos displayed on the clients websites

### ISSUE THREAD

**Issue by Jakob-tjek** [tjek/tjek-js-sdk#213]
We currently have "Powered by Incito" at the bottom of an Incito on our own platform:
![image](https://github.com/tjek/tjek-js-sdk/assets/72010544/99f49ba2-7c11-4159-95b9-e3d1aa8f8764)

We would also like to show this if the client uses our SDK on their own website.

By default, all existing clients should get this without doing anything. But it must be possible for us to disable it for specific clients.

**Comment by klarstrup** [comment]
Sounds like an issue for Bumblebee, where the code to decide to show this or not resides: https://github.com/tjek/bumblebee/blob/production/publication_core/incito-builder.js#L148-L167
