### ISSUE TITLE
Publish TypeScript declarations to NPM

### ISSUE THREAD

**Issue by boserup** [tjek/tjek-js-sdk#246]
We're currently using the SDK in a TypeScript project, and noticed that TypeScript types are not available via NPM. It would greatly improve our experience if the type declarations were either included in the package itself or published directly to NPM.

**Comment by klarstrup** [comment]
Hi I've had a go at implementing this and it is now published on the `@experimental` tag, please try that out and let me know if it fulfills your needs.

**Comment by klarstrup** [comment]
Types are published as of verso-browser@1.4.0, @tjek/sdk@0.16.0, shopgun-sdk@4.22.0 and incito-browser@2.6.0. Let me know if you need anything improved in them

**Comment by boserup** [comment]
That makes sense. We were able to resolve `V2Hotspot` from `shopgun-sdk`, and some of the other types we used. However `PagedViewer` from `PagedPublicationKit` is still only available via the kit-import.

<img width="678" alt="Screenshot 2024-09-09 at 13 02 23" src="https://github.com/user-attachments/assets/436db77f-7c1c-477a-b73a-da5c024631b3">

The same goes for `PagedPublicationEventTracking` (`lib/kits/paged-publication/event-tracking`).

Those two are the only remaining unresolved types we are using as of today.

**Comment by klarstrup** [comment]
I would suggest that for the time being you derive those type from the related classes(i.e. `ReturnType<IncitoPublicationBootstrapper["createViewer"]>` and `ReturnType<IncitoPublicationBootstrapper["createViewer"]>['_eventTracking']`) while we at Tjek figure out the long-term approach for the type exports of this package.
