### ISSUE TITLE
Remove 'display: box' from CSS output

### ISSUE THREAD

**Issue by boserup** [tjek/tjek-js-sdk#248]
The CSS output in `sgn-sdk.css` contains two occurrences of `display: box`. which is outdated and no longer supported by modern browsers. The `display: box` property has been replaced by `display: flex` in the final flexbox specification.

**Comment by boserup** [comment]
For context, we use Vite in our build pipeline, and it outputs a warning about using `display: box ` when building our application with the CSS provided by your SDK:

``` bash
 WARN  [vite:css] You should write display: flex by final spec instead of display: box
 ```

**Comment by klarstrup** [comment]
This is caused by our ancient stylus library `nib` trying to be a bit too backwards compatible, fixed.
